### ISSUE TITLE
Rocket's model is in the floor after a recent update

### ISSUE THREAD

**Issue by Moffein** [ToastedOven/CustomEmotesAPI#13]
https://github.com/Moffein/RocketSurvivor/issues/15
Forwarding this bug to here, noticing that Rocket's model is clipped into the floor after one of the recent updates.
Tested this with just Rocket and CustomEmotesAPI, as well as the profile submitted in the above issue.

**Comment by ToastedOven** [comment]
Just letting you know, was absolutely on my end because I have the stupid. It has been fixed in the most recent CustomEmotesAPI patch
