### ISSUE TITLE
Bug / Issue

### ISSUE THREAD

**Issue by EngineerTF2007** [ToastedOven/CustomEmotesAPI#18]
I came across bugs in the recent update of your mod, I believe, and when using emotions after their end or simply at their own request, ANY character gets into a certain G pose or A pose - the default one, so to speak. Don't know what to do with it?

https://github.com/user-attachments/assets/7cfa8e44-9407-4f05-872b-916652aa3402

**Comment by ToastedOven** [comment]
Can you send me a log from this run and also a profile code so that I can test it on my end?

**Comment by EngineerTF2007** [comment]
Ok, gimme a second

**Comment by EngineerTF2007** [comment]
01925022-6e5a-6c42-8736-fb2c0016c392 - Profile code
My BepInex console menu just not loading when i start game in r2modman, but all mods are loading at the end.

**Comment by EngineerTF2007** [comment]
And uh my DebugToolkit by IHarbHD was spamming this: FormatException: input string was not in a correct format.
No matter what i do, just respawn or use an emote

**Comment by ToastedOven** [comment]
your log can be found here 
![explorer_yp3VoVSuIs](https://github.com/user-attachments/assets/8613df6e-3858-4cfd-97ca-47fe3d2ddd99)

**Comment by ToastedOven** [comment]
I'm not getting the errors on my end, could be worth re-importing your profile with a cleared cache if the log file doesn't provide results

**Comment by EngineerTF2007** [comment]
And if I clear the cache profile and install it again through the code, will my progress be erased? **(in terms of mods**)

**Comment by EngineerTF2007** [comment]
[zipped_log.zip](https://github.com/user-attachments/files/17240998/zipped_log.zip) here's the log

**Comment by EngineerTF2007** [comment]
If you are worried about the presence of viruses, then you can check using VirusTotal or other programs:
https://www.virustotal.com/gui/file/e238c5f8fded2223cb5ada8e6fe8f2b63dc9d7171bdf32fbf4224dbb59a5df6a?nocache=1

**Comment by EngineerTF2007** [comment]
Please do not ignore that 😭

**Comment by ToastedOven** [comment]
sorry forgot to get back to this, I found the issue, seems like I a string parse wasn't working properly, I just have to set it up as InvariantCulture so it works with your system's default characters, I'll get this pushed out in a bit

**Comment by ToastedOven** [comment]
pushed the fix, should be good in 2.7.2

**Comment by EngineerTF2007** [comment]
Love you babe ❤️ 😽
