### ISSUE TITLE
Inanimate Void Fiend/Artificer

### ISSUE THREAD

**Issue by ADumCabbit** [ToastedOven/CustomEmotesAPI#2]
Putting this here as of version 1.2.3 has caused both Artificer and Void Fiend to be stuck within the 1st frame of their exiting/teleport animation, unable to display any vanilla animations they would normally do like shooting, running, etc. Emotes still seem to be usable, helps remove the glow they would initially have and other effects, such as void fiend movement effects staying on him after exiting,

This issue seems to be only with those two, every other survivor included the newly supported ones are fine at least in singleplayer, unsure on multiplayer. I have heard from a friend that paladin emotes weren't showing up for him as the host but worked fine for his friend playing paladin.

![20220414160719_1](https://user-images.githubusercontent.com/103690912/163472382-cac4d297-7408-4548-8e3b-b97f599e86c0.jpg)
![20220414160753_1](https://user-images.githubusercontent.com/103690912/163472383-064ecb1b-b4e4-42b5-bcf4-5e1ca41e8296.jpg)
![20220414161638_1](https://user-images.githubusercontent.com/103690912/163472385-b7dd3cd1-aed6-4401-ac78-531e2556d33d.jpg)
.

**Comment by ToastedOven** [comment]
Fixed with 1.3.0
