### ISSUE TITLE
Acrid's emote scaling is wrong

### ISSUE THREAD

**Issue by SSM240** [ToastedOven/CustomEmotesAPI#21]
I believe Acrid is being treated as _much_ larger than he actually is for emotes' size scaling effects. When the model spawns props or visual effects, they're much bigger than they're supposed to be, and conversely, if he's being scaled down to a certain size, he's much smaller than he should be.

A couple examples (with the "Summertime" and "Flippin' Awesome" emotes respectively):
![image](https://github.com/user-attachments/assets/8ab84b40-5c4f-4e66-95f8-816906b8b640)
![image](https://github.com/user-attachments/assets/9a9c1d95-f97a-4c19-af3c-08073e724c72)

**Comment by ToastedOven** [comment]
yeah seems like the update broke a lot of scales, gonna have to do a deep dive into this

**Comment by ToastedOven** [comment]
Fixed in 2.8.2
