### ISSUE TITLE
New Update Removes Paladin's Animations

### ISSUE THREAD

**Issue by TrueMemeKing** [ToastedOven/CustomEmotesAPI#3]
toggling custom emotes API off returns his animations to normal, but having the API installed causes him to slide around in a default animation pose.

In multiplayer, Miner also seems to be unanimated for other players but appears fine to the player, and House's legs are a little... noodley whenever he's not emoting. Not sure if any other characters suffer from no animations in multiplayer as I wasn't able to do any detailed testing with characters.

**Comment by ToastedOven** [comment]
Can you send your .log file and also a modlist? I have tried this on my local machine and paladin seems fine but I'm getting multiple reports saying he just slides. Miner and house issues are noted and I'm working on fixing them

**Comment by TrueMemeKing** [comment]
[LogOutput.log](https://github.com/ToastedOven/CustomEmotesAPI/files/8498409/LogOutput.log)
bbepis-BepInExPack-5.4.1903
RiskofThunder-HookGenPatcher-1.2.3
tristanmcpherson-R2API-4.3.5
SaltAndViChips-LeanFiend-1.0.5
William758-ZetAspects-2.7.4
EnforcerGang-HAND_OVERCLOCKED-0.2.6
EnforcerGang-SniperClassic-1.0.12
Gnome-ChefMod-2.0.17
KubeRoot-CommandQueue-1.3.3
Dragonyck-Bomber-1.2.1
Paladin_Alliance-PaladinMod-1.5.8
EnforcerGang-Enforcer-3.3.8
12GaugeAwayFromFace-Commando_Elite_Trooper_Skin-1.2.2
TheMysticSword-MysticsRisky2Utils-2.0.2
TheMysticSword-MysticsItems-2.0.11
niwith-DropinMultiplayer-2.0.0
Bog-VoidFiendTweaks-0.9.2
TheTimesweeper-SurvivorSortOrder-0.1.2
egpimp-EggsUtils-1.1.2
egpimp-EggsSkills-2.1.3
MagnusMagnuson-BiggerBazaar-1.13.5
nayDPz-Dancer-0.9.71
JavAngle-TheHouse-1.6.1
Heyimnoob-SkillsFromtheDeepEnd-1.9.0
FunkFrog-and-Sipondo-ShareSuite-2.7.0
IHarbHD-DebugToolkit-3.7.1
Moffein-MobileTurretBuff-1.1.8
NekuSoul-ShopsOnly-3.0.3
Moffein-No_Void_Allies-1.0.6
XoXFaby-BetterUI-2.5.10
TailLover-DinoMulT-1.0.3
Moffein-Sacrifice_Tweaks-1.0.6
Harb-AssetPlusRequester-1.0.0
EnforcerGang-MinerUnearthed-1.6.9
WPhantom-Synced_Turrets-0.0.2
Vegetableaux-Save_Turrets_From_Underpopulation-1.0.2
HIFU-HuntressAutoaimFix-1.0.8
HIFU-HIFUHuntressTweaks-4.2.1
Moffein-Bandit_Tweaks-1.7.1
duckduckgreyduck-Transgendence-1.0.1
bobblet-UltrakillV1_Bandit_Skin-1.0.4
KingEnderBrine-ScrollableLobbyUI-1.7.4
RuneFox237-LoonaRailgunner-1.0.0
ArvolyMods-LigmaObliterateRedone-1.0.5
ThinkInvis-TILER2-6.3.0
ThinkInvis-TinkersSatchel-1.13.2
LexLamb-MechArtificer-0.0.1
SpikestripModding-More_Difficulties-1.2.1
MAVRI-CaptainUnderglowDrip-1.1.1
Gameguide-FreddyFazbearEngieSkin-1.0.21
12GaugeAwayFromFace-Bandit_UES_Trooper_Skin-1.2.1
KingEnderBrine-LobbySkinsFix-1.2.0
Dragonyck-Gunslinger-1.9.0
Anreol-ReleasedFromTheVoid-0.0.3
RetroInspired-Railgunner_Skins-1.0.2
Muugiboy-Remastered-1.0.8
Serynn-SpiritBlossomKindredHuntress-1.1.0
Risky_Lives-RiskyMod-0.6.11
XoXFaby-MMHOOK_Standalone-1.0.3
konomiyu-CustomChaosPool-1.1.4
duckduckgreyduck-ArtificerExtended-3.3.0
Evaisa-ChatSounds-2.0.2
Moffein-Risky_Artifacts-1.4.7
Moffein-Bandit_Dynamite_Toss-1.0.8
dotflare-LostThroughTimeSkinPack-1.0.7
ThinkInvis-ClassicItems-6.1.2
xiaoxiao921-BadAssEngi-1.3.6
Heyimnoob-BioDroneAcrid-1.0.0
Catsune-Voidbound_Railgunner_Skin-1.0.1
Groove_Salad-NetworkedItemTransformNotifications-1.0.0
KrononConspirator-MadVeteran_Skinpack-1.2.0
Wolfo-WolfoQualityOfLife-2.0.2
Wolfo-ArtifactOfDissimilarity-2.0.0
Rune580-Risk_Of_Options-2.3.1
MetrosexualFruitcake-CustomEmotesAPI-1.3.2
MetrosexualFruitcake-TPose-4.0.0
Bubbet-WhatAmILookingAt-1.4.4
MetrosexualFruitcake-BadAssEmotes-1.1.3
JustForMemes-SenatorArmstrongLoader-1.0.1
nobleRadical-Resonance_Field_Generator-1.1.2
DrBibop-VRAPI-1.0.1
dgosling-dgoslings_Samus_Mod-2.1.8
Heyimnoob-UsurperPaladin-1.0.0

Sorry about the ridiculously large list, I have mod hoarding issues

**Comment by ToastedOven** [comment]
Oh sorry, I should have replied here, I fixed both the no-animation issues if you download the most recent version. The House still has L O N G legs but that will be addressed soonish
