### ISSUE TITLE
Possible BUG Detected: Possible bug of the API with the use of the animation mod.

### ISSUE THREAD

**Issue by KaitoXion** [ToastedOven/CustomEmotesAPI#9]
When dancing, looks like the mod or API was trying to copy the pixel in the area so that it does not felt off; or it could be that the added bone by the API just happens to overlap with the pixel in the image below. As the tail is pretty huge, so the bone probably overlaps with it. Causing pixels to be dragged in a weird way.

Am a noop at this. so I don't know what that center point is called. Vertex is the word for it maybe?

Emote Mod used:
BadAssEmotes
Caramelldansen

Skin:
https://thunderstore.io/package/Nix/KunouCommando/

![image](https://github.com/ToastedOven/CustomEmotesAPI/assets/23281263/92114772-0706-49fc-a7bf-fe09355b6eb4)

I don't know if it will be consider a bug, but is something to take note of.

Looking forward to expert comments.
![image](https://github.com/ToastedOven/CustomEmotesAPI/assets/23281263/332eb1c4-6b33-46d5-8af1-ed83a3da756c)

**Comment by ToastedOven** [comment]
looks like a part of the tail is weight painted to the guns. When emoting the guns are simply moved a million units away to hide them. Whoever weight painted this model accidentally painted a bit of the tail to said guns. Not noticeable in normal gameplay but if the guns move far away it causes this

**Comment by Rune580** [comment]
Seems to me like that vertex was weight painted to the wrong bone. Try getting in touch with the mod author for that skin if you haven't already.

**Comment by KaitoXion** [comment]
Hmm, I think I sort of get the idea of it.
According to the author, physic is added to the tail part of this skin. So I can see that or I assume that there is an additional vertex point specially for the tail.

The buggy image is where the connection point of the tail and the body is at. That point don't change no matter how the dance moves changes.

@ToastedOven 
> "Whoever weight painted this model accidentally painted a bit of the tail to said guns.".

-> This am not sure yet. I don't really get the idea where a bit of the said tail is painted to the said guns because I didn't saw any of the tail colors on the guns or vise versa.
However, it could be color changes that cause detection impossible when in-game. I'll try to contact the author and see if the author had any comment. 

@Rune580 
>"Seems to me like that vertex was weight painted to the wrong bone."

->May I know by "wrong bone", you meant the default bone of the original skin right?
Let say if another 1 vertex / connection point is created by the author to add physic to the tail, the buggy situation will occur I presume.
Will there be any way to get both the physic of the tail still work as well as solving this bug? I tried to read through blender, well no idea for me. (Am noop)
While I don't think this is something that can be easily solve since it may be due to the original bones of ROR 2, I'll still attempt to let the author know about it.

Thank you both for your kind reply. Really appreciate your great insight to my inquiry.

**Comment by Rune580** [comment]
we've done some quick testing with the skin mod on it's own, it seems like it wasn't correctly weight painted.

**Comment by Rune580** [comment]
I'd like to check the weight painting myself, but it doesn't seem like the source files are available.

**Comment by ToastedOven** [comment]
https://github.com/ToastedOven/CustomEmotesAPI/assets/49164897/be0d38e5-4e5a-4e37-b717-de2adfc08e27

yeah even with no emote mods installed it still has issues

**Comment by KaitoXion** [comment]
@Rune580 
> we've done some quick testing with the skin mod on it's own, it seems like it wasn't correctly weight painted.

->Yup, The author were contacted and reply had been received. Seem that author thinks the same and is thinking of taking a closer look.

> I'd like to check the weight painting myself, but it doesn't seem like the source files are available.

-> Thank you very much for your attempt and expert yet demonstration of great troubleshooting attempt as a real specialist.
Is true that there is no repository link available. Think is that way for a good reason. Think is something deserve great respect for.  

@ToastedOven 
> Risk_of_Rain_2_RnAYcxpWx7.mp4
> 
> yeah even with no emote mods installed it still has issues

-> Wow, I never had the idea to test it this way before. Cause I been running around and yet didn't manage to spot it. 
I haven't tried to put it up close to test it from the side cause I was thinking that the vertex will move together with everything.
That's a pro / real expert, you understood something well. 
The author were contacted and a reply had been received, Author be taking a closer look. Thank you very much for the video, I think it really helps to clear things out so much. It's very helpful of you.

To conclude for now, the author were notified with details from this discussion. Author too thinks the same and is thinking of taking a closer look. With the given video, I think it will be even more helpful.
Much appreciated from me guys. 

Shall we consider as this "issue" or discussion close?
I or author may inquire something later. Though I can say nothing of certain for now.
I could monitor and close it as needed. Owner will give the call here I guess.

**Comment by ToastedOven** [comment]
I think we are good for now, you can reopen if the model gets repainted and the issue is still present
